### PR TITLE
Make it German

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Comment by woolfg** [comment]
the readme is auto generated, so it has to be changed in the template in `https://github.com/EngineeringKiosk/GermanTechPodcasts/blob/main/assets/README.template` but we have to discuss first how we want to proceed with the language in #29

**Comment by andygrunwald** [comment]
In https://github.com/EngineeringKiosk/GermanTechPodcasts/blob/main/DEVELOPMENT.md we describe a bit the generated README part.

**Comment by szepeviktor** [comment]
Ich lerne Deutsch. Ich möchte es meiner Lehrerin zeigen.

**Comment by szepeviktor** [comment]
Closed by #112

**Pull request closed without merging**
